### ISSUE TITLE
i don't understand the instructions .

### ISSUE THREAD

**Issue by TheGodOfNoodles** [GameCodex/Apex-Legends-Hack-Esp-Aimbot-Source#1]
i debugged it but i don't understand what you mean by open exe and if u mean attach it to apex directly it says access denied ( sorry if im being stupid im new to this )

**Comment by dontbestupid** [comment]
> 
> 
> i debugged it but i don't understand what you mean by open exe and if u mean attach it to apex directly it says access denied ( sorry if im being stupid im new to this )

This guy is trying to infect people with his Github Repositiries. Is doing a new account every week because he's getting reported, then banned by github support. He is acting against the terms of github and tries to violate the community & users.

I'm sorry to tell you this, but the source code repositorie here not even includes an half working apex cheat. its stolen code from public cheats throwed together. 

And now the thing where you may get infected. The ".sln" files to open the sourcecode from this guy are not real ".sln" files. A normal .sln file for Visual Studio is builded like a config and can easily be editen with notepad. But this guy's .sln files are just an application packed with some virus maybe. (i havent reversed his shit in vm so far, but may do in future.) Also a normal .sln file does not even have this filesize. If you look at normal c++ sourcecodes on github, you will notice that normalö .sln files can be opened and readed directly via github. Which is not the case here either.

Hope you are not part of his botnet or trojan virus now.

**Comment by TheGodOfNoodles** [comment]
ye i realised after and sorted it out so yep ^^^^^^^^^^ 100% true

**Comment by GameCodex** [comment]
> > i debugged it but i don't understand what you mean by open exe and if u mean attach it to apex directly it says access denied ( sorry if im being stupid im new to this )
> 
> This guy is trying to infect people with his Github Repositiries. Is doing a new account every week because he's getting reported, then banned by github support. He is acting against the terms of github and tries to violate the community & users.
> 
> I'm sorry to tell you this, but the source code repositorie here not even includes an half working apex cheat. its stolen code from public cheats throwed together.
> 
> And now the thing where you may get infected. The ".sln" files to open the sourcecode from this guy are not real ".sln" files. A normal .sln file for Visual Studio is builded like a config and can easily be editen with notepad. But this guy's .sln files are just an application packed with some virus maybe. (i havent reversed his shit in vm so far, but may do in future.) Also a normal .sln file does not even have this filesize. If you look at normal c++ sourcecodes on github, you will notice that normal .sln files can be opened and readed directly via github. Which is not the case here either.
> 
> Hope you are not part of his botnet or trojan virus now.

a really good explanation
